import { UserContext } from "../../core/user-context.js";
import { Permissions } from "../../core/permissions.js";
import { ToastService } from "../../core/toast-service.js";
import { ModalService } from "../../core/modal-service.js";
import { AdminReadService } from "../../services/admin-read-service.js";
export async function renderAdminView(outlet){const user=UserContext.requireUser();if(!Permissions.isAdmin())return renderDenied(outlet,user);outlet.innerHTML=loadingCard("Đang tải thống kê quản trị…");try{const summary=await AdminReadService.summary();outlet.innerHTML=`<section class="page-card"><div class="page-header"><div><span class="page-eyebrow">QUẢN TRỊ HỆ THỐNG</span><h2>Trung tâm quản trị</h2><p>Thống kê dữ liệu nền và quản trị vòng đời nhiệm vụ.</p></div><span class="role-badge">ADMIN</span></div><div class="success-banner">Tài khoản <strong>${escapeHtml(user.fullName||user.email)}</strong> có quyền quản trị.</div><div class="summary-grid compact-grid">${metric("Kỳ đánh giá",display(summary.periods))}${metric("Tài khoản hoạt động",display(summary.activeUsers))}${metric("Đầu việc chuẩn",display(summary.activeStandardTasks))}${metric("Thông tin cần kiểm tra",summary.warnings.length)}</div><div class="admin-tools-grid"><a class="admin-action-card" href="#/kpi/periods"><span>🗓️</span><strong>Quản lý kỳ đánh giá</strong><small>Tạo, sửa, kích hoạt và kết thúc kỳ đánh giá.</small></a><button id="btnAdminCheckData" class="admin-action-card" type="button"><span>🔍</span><strong>Kiểm tra dữ liệu</strong><small>Kiểm tra khả năng truy cập dữ liệu.</small></button><button id="btnAdminAudit" class="admin-action-card" type="button"><span>📜</span><strong>Nhật ký hệ thống</strong><small>Theo dõi lịch sử cập nhật nhiệm vụ.</small></button><button id="btnAdminCleanup" class="admin-action-card danger" type="button"><span>🗑️</span><strong>Xóa dữ liệu kỳ</strong><small>Xóa dữ liệu kỳ sau khi đã in, ký và lưu hồ sơ giấy.</small></button></div>${summary.warnings.length?`<div class="warning-banner">Một số thông tin chưa truy cập được. Vui lòng kiểm tra quyền tài khoản.</div>`:'<div class="success-banner">Dữ liệu quản trị đã sẵn sàng.</div>'}</section>`;document.getElementById("btnAdminCheckData")?.addEventListener("click",()=>ToastService.success("Đã kiểm tra dữ liệu nền."));document.getElementById("btnAdminAudit")?.addEventListener("click",()=>ToastService.info("Nhật ký hệ thống sẽ được kết nối ở phiên bản sau."));document.getElementById("btnAdminCleanup")?.addEventListener("click",async()=>{await ModalService.open({title:"Chế độ chỉ đọc",message:"Việc xóa dữ liệu kỳ được thực hiện trong màn hình Quản lý kỳ, sau khi kỳ đã kết thúc và hồ sơ giấy đã được lưu.",confirmText:"Đã hiểu",showCancel:false,danger:true});});}catch(error){outlet.innerHTML=errorCard("Không thể tải dữ liệu quản trị",error);}}
function renderDenied(outlet,user){outlet.innerHTML=`<section class="page-card"><div class="empty-state"><div class="empty-icon">🔒</div><strong>Không có quyền truy cập</strong><p>Tài khoản ${escapeHtml(user.fullName||user.email)} không có vai trò ADMIN.</p><a class="secondary-button" href="#/dashboard">Quay về Trang chủ</a></div></section>`;}
function metric(label,value){return `<article class="summary-card"><span>${label}</span><strong>${value}</strong><small>Dữ liệu thật</small></article>`;}
function display(value){return value===null?"—":value;}
function loadingCard(message){return `<section class="page-card"><div class="empty-state"><div class="empty-icon">⏳</div><strong>${escapeHtml(message)}</strong></div></section>`;}
function errorCard(title,error){return `<section class="page-card error-card"><h2>${escapeHtml(title)}</h2><p>${escapeHtml(error?.message||"Lỗi không xác định")}</p></section>`;}
function escapeHtml(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
