import { UserContext } from "../../core/user-context.js";
import { Permissions } from "../../core/permissions.js";
import { ToastService } from "../../core/toast-service.js";
import { ModalService } from "../../core/modal-service.js";
import { AdminReadService } from "../../services/admin-read-service.js";
export async function renderAdminView(outlet){const user=UserContext.requireUser();if(!Permissions.isAdmin())return renderDenied(outlet,user);outlet.innerHTML=loadingCard("Đang tải thống kê quản trị…");try{const summary=await AdminReadService.summary();outlet.innerHTML=`<section class="page-card"><div class="page-header"><div><span class="page-eyebrow">QUẢN TRỊ HỆ THỐNG • READ ONLY</span><h2>Trung tâm quản trị</h2><p>Thống kê dữ liệu nền thật, không ghi hoặc xóa dữ liệu.</p></div><span class="role-badge">ADMIN</span></div><div class="success-banner">Tài khoản <strong>${escapeHtml(user.fullName||user.email)}</strong> có quyền quản trị.</div><div class="summary-grid compact-grid">${metric("Kỳ đánh giá",display(summary.periods))}${metric("Tài khoản hoạt động",display(summary.activeUsers))}${metric("Đầu việc chuẩn",display(summary.activeStandardTasks))}${metric("Collection lỗi quyền",summary.warnings.length)}</div><div class="admin-tools-grid"><a class="admin-action-card" href="#/kpi/periods"><span>🗓️</span><strong>Quản lý kỳ đánh giá</strong><small>Xem dữ liệu evaluationPeriods.</small></a><button id="btnAdminCheckData" class="admin-action-card" type="button"><span>🔍</span><strong>Kiểm tra dữ liệu</strong><small>Hiển thị kết quả đọc collection.</small></button><button id="btnAdminAudit" class="admin-action-card" type="button"><span>📜</span><strong>Nhật ký hệ thống</strong><small>Chưa kết nối trong Production 3C.</small></button><button id="btnAdminCleanup" class="admin-action-card danger" type="button"><span>🗑️</span><strong>Xóa dữ liệu kỳ</strong><small>Đã vô hiệu hóa trong chế độ Read Only.</small></button></div>${summary.warnings.length?`<div class="warning-banner">Không đọc được: ${summary.warnings.map(escapeHtml).join(", ")}. Kiểm tra Firestore Rules.</div>`:'<div class="success-banner">Đã đọc thành công các collection quản trị nền.</div>'}</section>`;document.getElementById("btnAdminCheckData")?.addEventListener("click",()=>ToastService.success("Đã kiểm tra dữ liệu nền ở chế độ chỉ đọc."));document.getElementById("btnAdminAudit")?.addEventListener("click",()=>ToastService.info("Nhật ký hệ thống sẽ được kết nối ở phiên bản sau."));document.getElementById("btnAdminCleanup")?.addEventListener("click",async()=>{await ModalService.open({title:"Chế độ chỉ đọc",message:"Production 3C không cho phép xóa dữ liệu.",confirmText:"Đã hiểu",showCancel:false,danger:true});});}catch(error){outlet.innerHTML=errorCard("Không thể tải dữ liệu quản trị",error);}}
function renderDenied(outlet,user){outlet.innerHTML=`<section class="page-card"><div class="empty-state"><div class="empty-icon">🔒</div><strong>Không có quyền truy cập</strong><p>Tài khoản ${escapeHtml(user.fullName||user.email)} không có vai trò ADMIN.</p><a class="secondary-button" href="#/dashboard">Quay về Trang chủ</a></div></section>`;}
function metric(label,value){return `<article class="summary-card"><span>${label}</span><strong>${value}</strong><small>Dữ liệu thật</small></article>`;}
function display(value){return value===null?"—":value;}
function loadingCard(message){return `<section class="page-card"><div class="empty-state"><div class="empty-icon">⏳</div><strong>${escapeHtml(message)}</strong></div></section>`;}
function errorCard(title,error){return `<section class="page-card error-card"><h2>${escapeHtml(title)}</h2><p>${escapeHtml(error?.message||"Lỗi không xác định")}</p></section>`;}
function escapeHtml(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
