import { Permissions } from "../../core/permissions.js";
import { PeriodReadService } from "../../services/period-read-service.js";
import { TaskReadService } from "../../services/task-read-service.js";
export async function renderPlansView(outlet){outlet.innerHTML=loadingCard("Đang tải dữ liệu kế hoạch quý…");try{const [periods,tasks]=await Promise.all([PeriodReadService.list(),TaskReadService.list()]);const active=PeriodReadService.active(periods);const scoped=active?tasks.filter(task=>task.periodId===active.id||task.periodId===active.code):[];const approved=scoped.filter(task=>String(task.planApprovalStatus||"").toUpperCase()==="APPROVED");const pending=scoped.filter(task=>String(task.planApprovalStatus||"").toUpperCase()==="PENDING_APPROVAL");const scoreA=approved.filter(task=>task.includedInA===true).reduce((sum,task)=>sum+Number(task.maximumConvertedScore||0),0);outlet.innerHTML=`<section class="page-card"><div class="page-header"><div><span class="page-eyebrow">KẾ HOẠCH KPI • READ ONLY</span><h2>Kế hoạch nhiệm vụ quý</h2><p>Đọc nhiệm vụ đã liên kết với kỳ đánh giá hiện tại.</p></div><span class="status-pill ${active?"success":"neutral"}">${active?escapeHtml(active.name||active.code||active.id):"Chưa có kỳ hoạt động"}</span></div><div class="summary-grid compact-grid">${card("A – Kế hoạch",formatNumber(scoreA))}${card("Đã duyệt",approved.length)}${card("Chờ duyệt",pending.length)}${card("Nhiệm vụ trong kỳ",scoped.length)}</div><div class="tab-bar"><button class="tab-button active" type="button">Nhiệm vụ của tôi</button>${Permissions.canApprovePlan()?'<button class="tab-button" type="button">Chờ duyệt</button>':""}${Permissions.canLockDepartmentPlan()?'<button class="tab-button" type="button">Khóa kế hoạch</button>':""}</div>${active?renderTasks(scoped):'<div class="empty-state"><div class="empty-icon">📊</div><strong>Chưa có kỳ đánh giá hoạt động</strong></div>'}</section>`;}catch(error){outlet.innerHTML=errorCard("Không thể tải kế hoạch quý",error);}}
function renderTasks(tasks){if(!tasks.length)return `<div class="empty-state"><div class="empty-icon">📊</div><strong>Chưa có nhiệm vụ liên kết kỳ hiện tại</strong></div>`;return `<div class="data-list">${tasks.map(task=>`<article class="data-row"><div class="data-row-main"><strong>${escapeHtml(task.title||task.taskCode||task.id)}</strong><small>${escapeHtml(task.ownerName||task.createdByName||"Chưa phân công")}</small></div><div class="data-row-meta"><span class="status-pill neutral">${escapeHtml(task.planApprovalStatus||"CHUA_DUYET")}</span><small>${task.includedInA===true?"Tính vào A":"Không tính vào A"}</small></div></article>`).join("")}</div>`;}
function card(label,value){return `<article class="summary-card"><span>${label}</span><strong>${value}</strong><small>Dữ liệu thật</small></article>`;}
function formatNumber(value){return new Intl.NumberFormat("vi-VN",{maximumFractionDigits:1}).format(Number(value||0));}
function loadingCard(message){return `<section class="page-card"><div class="empty-state"><div class="empty-icon">⏳</div><strong>${escapeHtml(message)}</strong></div></section>`;}
function errorCard(title,error){return `<section class="page-card error-card"><h2>${escapeHtml(title)}</h2><p>${escapeHtml(error?.message||"Lỗi không xác định")}</p></section>`;}
function escapeHtml(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
